apiVersion: v1
kind: ReplicationController
metadata:
  name: openmrs-rc
spec:
  replicas: 3
  selector:
    app: openmrs
    version: v1
  template:
    metadata:
      labels:
        app: openmrs
        version: v1
    spec:
      containers:
      - name: openmrs-pod
        image: shaikkhajaibrahim/openmrs
        ports:
        - containerPort: 8080
